// src/redux/actions/types.js

export const PURCHASE_PROPERTY_REQUEST = 'PURCHASE_PROPERTY_REQUEST';
export const PURCHASE_PROPERTY_SUCCESS = 'PURCHASE_PROPERTY_SUCCESS';
export const PURCHASE_PROPERTY_FAILURE = 'PURCHASE_PROPERTY_FAILURE';

export const RENT_PROPERTY_REQUEST = 'RENT_PROPERTY_REQUEST';
export const RENT_PROPERTY_SUCCESS = 'RENT_PROPERTY_SUCCESS';
export const RENT_PROPERTY_FAILURE = 'RENT_PROPERTY_FAILURE';
